### ISSUE TITLE
Troubles grabbing settings.json

### ISSUE THREAD

**Issue by ColeScheller** [team3997/ChickenVision#10]
I have the newest available image for frcvision

When I attempt to upload your code I get the following error:

```
Traceback (most recent call last):

  File "./uploaded.py", line 684, in <module>

    if not readConfig():

  File "./uploaded.py", line 631, in readConfig

    j = json.load(f)

  File "/usr/lib/python3.5/json/__init__.py", line 265, in load

    return loads(fp.read(),

  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 174: ordinal not in range(128)

Waiting 5 seconds...
```

I attempted to comment that section out, to no avail.

I apologize if this is clear, I am new and rather frustrated with the lack of documentation on the frcvision environment.

**Comment by codeNinjaDev** [comment]
Try running ./runInteractive

**Comment by ColeScheller** [comment]
> Try running ./runInteractive

Exact same error, what was I doing by running that?

**Comment by codeNinjaDev** [comment]
Hmm never seen this before. Try restarting pi from webdashboard, then you won't need to use terminal hopefully

**Comment by codeNinjaDev** [comment]
It should automatically run when restarted

**Comment by ColeScheller** [comment]
Still getting the same error. Do I need to supply some sort of settings file?

**Comment by codeNinjaDev** [comment]
I didn't need to. Is camera connected?

**Comment by ColeScheller** [comment]
Yes. It's a Microsoft 300 Lifecam HD (or something like that) and it's plugged into the pi directly.

**Comment by codeNinjaDev** [comment]
try running example program? Never seen this before.

**Comment by ColeScheller** [comment]
running "Built-In multi-camera streaming" from the dropdown works, but downloading the example program and running that doesn't work, neither does the python example from the dropdown.

**Comment by ColeScheller** [comment]
The same error results

**Comment by codeNinjaDev** [comment]
That's very weird. Try imaging os again. Plus I (someone else, unrelated) found a bug in chicken vision that I need to fix

**Comment by codeNinjaDev** [comment]
If that continues, I would make an issue on wpilib frcvision page

**Comment by ColeScheller** [comment]
Reimaged, still not working. I'm going to take your advice and open and issue over there. Thanks for the help.

**Comment by ColeScheller** [comment]
Went over to the frcvision repo, we figured it out. On line 94 a 3rd parameter needs to be passed to open(), 
```
encoding="utf-8"
```
because when the pi makes the lifecam url it adds unicode (the trademark symbol) causing it to crash because it is expecting ascii only

**Comment by codeNinjaDev** [comment]
Wow, congrats on getting that fixed. I would never have figured that out
