### ISSUE TITLE
'[...] not in biggestCnts' throws ValueError

### ISSUE THREAD

**Issue by fovea1959** [team3997/ChickenVision#11]
We are occasionally having Exceptions thrown on (currently line 430 of master):

```
                    # Appends important info to array
                    if not biggestCnts:
                        biggestCnts.append([cx, cy, rotation, cnt])
                    elif [cx, cy, rotation, cnt] not in biggestCnts:
                        biggestCnts.append([cx, cy, rotation, cnt])
```

we are seeing

```
File "./uploaded.py", line xxx, in findTape

    elif[cx, cy, rotation, cnt] not in biggestCnts:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I did some offline testing, and you will sometimes get this ValueError if there is a numpy array in the list you are checking to see if it's present in the biggestCnts list of lists. cnt *is* a numpy array, hence the "boom".

I can't make it happen consistently, but I noticed that the cnt we are putting into biggestCnts is never used again in findTape. Can we just not put it in the list, and make the problem go away?

Do we even need to check to see if [cx, cy, rotation, cnt] already exists in biggestCnts? What's the chance of having two contours in the same image with the exist same center [cx, cy] and shape[cnt]?

Do we need to check if biggestCnts is empty before adding it?

Can we reduce lines 430-433 to:
```
                    biggestCnts.append([cx, cy, rotation])
```

**Comment by codeNinjaDev** [comment]
Thanks for alerting me to the problem. I have had this problem before, but I mistakenly thought I fixed it. 

From early testing, I found that the program does find and store duplicates in biggestCnts. However, I think you are correct in being able to remove cnt from that array if it's not being used.

Thank you again for finding this bug because I currently don't have a way of finding bugs since we dismantled programming bot

**Comment by codeNinjaDev** [comment]
I was able to set up another raspberry pi and removed cnt from the array and haven't got any errors

**Comment by codeNinjaDev** [comment]
Specifically truth value errors

**Comment by codeNinjaDev** [comment]
Have you run into this issue again, if not I will commit the change removing cnt from biggestCnts

**Comment by codeNinjaDev** [comment]
I removed cnt from biggest cnt
