### ISSUE TITLE
Uploading Code to Raspberry Pi

### ISSUE THREAD

**Issue by Bananajojo123** [team3997/ChickenVision#7]
So, you have a new version and I took it and want to use it. How do apply this to the vision of the Raspberry Pi? When I upload this as an application, it doesn't work.
![image](https://user-images.githubusercontent.com/20143106/52156396-4e506000-2645-11e9-8df6-0ee060f1a78f.png)

It gives the stream a 404 error.

![image](https://user-images.githubusercontent.com/20143106/52156430-67f1a780-2645-11e9-829e-39d23d1a70e3.png)

Also how do you implement the GRIP pipeline? I have exported it, and don't know how to use it.

![image](https://user-images.githubusercontent.com/20143106/52156461-91aace80-2645-11e9-81a6-0ea1407f30d6.png)

**Comment by codeNinjaDev** [comment]
It looks like either camera is busy or chickenvision is crashing due to an error. 

The way you figure out is you look at console either by sshing into pi or using webdashboard. 

If camera is busy, shutdown pi (unplug it), unplug camera, plug camera back in, and power on pi. That fixed that for me.

If code error, post it here so I can fix it.

**Comment by codeNinjaDev** [comment]
Also look at wiki for using GRIP. I don't have any experience using GRIP pipelines, but I do use it to find the HSV values.

**Comment by Bananajojo123** [comment]
So I don't need GRIP at all? Your code does HSV already?

**Comment by codeNinjaDev** [comment]
Yes, but it if having trouble with tracking you can adjust hsv values.

**Comment by Bananajojo123** [comment]
Let me try your code then....

**Comment by Bananajojo123** [comment]
So I tested it and it still refuses to connect

![image](https://user-images.githubusercontent.com/20143106/52157517-ca9a7180-264c-11e9-900e-75c6bd827716.png)

**Comment by Bananajojo123** [comment]
And another thing, on line 730, you have an if statement with no colon!
