### ISSUE TITLE
Mask Not Being Applied

### ISSUE THREAD

**Issue by Bananajojo123** [team3997/ChickenVision#8]
The output image is not masked when applying HSV.

This is what we are seeing in the web app
![image](https://user-images.githubusercontent.com/20143106/52158944-0b00ec00-265b-11e9-8a91-c84a5177cbbd.png)

**Comment by codeNinjaDev** [comment]
By default, it tracks cargo. You can change that on line 736 by setting False to True

**Comment by codeNinjaDev** [comment]
It does that in threshold, but it doesn't push that mask to stream.
